package com.github.wanderwise_inc.app.ui

/* helps us avoid typos / inconsistencies between the test files and this file */
object TestTags {
  const val BOTTOM_NAV = "Bottom navigation bar"
  const val SEARCH_DROPDOWN = "Search Dropdown"
  const val OVERVIEW_SCREEN = "Overview Screen"
  const val LIKED_SCREEN = "Liked Screen"
  const val ITINERARY_LIST_SCROLLABLE = "Itinerary Scrollable List With Itineraries"
  const val ITINERARY_LIST_NULL = "Itinerary Scrollable List No Itineraries"
  const val ITINERARY_BANNER = "itinerary_banner"
  const val ITINERARY_BANNER_LIKE_BUTTON = "itinerary_banner_like_button"
  const val FILTER_PRICE_RANGE = "Filter Price Range"
  const val FILTER_TIME_RANGE = "Filter Time Range"
  const val SEARCH_BAR = "Search Bar"
  const val CATEGORY_SELECTOR = "Category Selector"
  const val CATEGORY_SELECTOR_TAB = "Category Selector Tab"
  const val NEW_CREATION_SCREEN = "New Creation Screen"
  const val NO_NEW_CREATION_SCREEN = "No New Creation Screen"
  const val CREATION_SCREEN_LOCATIONS = "Creation Screen Choose Locations"
  const val CREATION_SCREEN_DESCRIPTION_TITLE = "Creation Screen Choose Title and Description"
  const val CREATION_SCREEN_TITLE = "Creation Screen Choose Title"
  const val CREATION_SCREEN_DESCRIPTION = "Creation Screen Choose Description"
  const val CREATION_SCREEN_TAGS = "Creation Screen Choose Tags"
  const val CREATION_SCREEN_PREVIEW = "Creation screen preview"
  const val CREATION_SCREEN_PREVIEW_BUTTON = "Creation screen preview button"
  const val CREATION_SCREEN_PREVIEW_BANNER = "Creation Screen Preview Banner"
  const val CREATION_SCREEN_PREVIEW_ITINERARY = "Creation Screen Preview Itinerary"
  const val CREATION_SCREEN_NAV_BAR = "Creation Screen Top navigation bar"
  const val CREATION_FINISH_BUTTON = "Preview Finish Itinerary Creation Button"

  const val INVALID_INPUT = "invalid input"

  const val PRICE_SEARCH = "Price Search"
  const val TIME_SEARCH = "Time Search"
  const val SEARCH_ICON = "Search Icon"
  const val MAP_SCREEN = "Map Screen"
  const val MAP_PREVIEW_ITINERARY_SCREEN = "preview_itinerary_screen"
  const val MAP_GOOGLE_MAPS = "google_maps"
  const val MAP_MAXIMIZED_BANNER = "maximized_banner"
  const val MAP_MINIMIZED_BANNER = "minimized_banner"
  const val MAP_PROFILE_PIC = "profile_picture"
  const val MAP_CENTER_CAMERA_BUTTON = "center_camera_button"
  const val MAP_BANNER_BUTTON = "banner_button"
  const val MAP_ITINERARY_TITLE = "itinerary_title"
  const val MAP_ITINERARY_DESCRIPTION = "itinerary_description"
  const val MAP_USER_LOCATION = "user_location"
  const val MAP_NULL_ITINERARY = "null_location"
  const val PROFILE_SCREEN = "Profile Screen"
  const val FIRST_LOCATION = "First Location"
  const val SECOND_LOCATION = "Second Location"

  const val START_NEW_ITINERARY = "start_new_itinerary"
  const val HINT_POPUP = "hint_popup"
  const val HINT_POPUP_MESSAGE = "hint_popup_message"
}
